package com.roadtrip;

import com.parse.Parse;
import com.parse.ParseACL;
import com.parse.ParseObject;
import com.parse.ParseUser;

import android.app.Application;

public class RoadTripApplication extends Application {

	@Override
	public void onCreate() {
		super.onCreate();

		// Add your initialization code here
		Parse.initialize(this, "tlnGs4HObIIQR1fk9oKx6ISdS45J6fGbEu0Wvqww",
				"r0wa5xXwSz1sZOr2gobBT5GQ82Sk7ZM4AtyliIQl");

		ParseUser.enableAutomaticUser();
		ParseACL defaultACL = new ParseACL();

		// If you would like all objects to be private by default", remove this
		// line.
		defaultACL.setPublicReadAccess(true);

		ParseACL.setDefaultACL(defaultACL, true);
		ParseObject gameScore = new ParseObject("GameScore");
		gameScore.put("score", 1337);
		gameScore.put("playerName", "Sean Plott");
		gameScore.put("cheatMode", false);
		gameScore.saveInBackground();
		
		
		ParseObject adsd = new ParseObject("kur");
		adsd.put("asdf", "asdf");
		adsd.saveInBackground();
		ParseObject testObject = new ParseObject("Cities");
		testObject.put("1", false);
		testObject.saveInBackground();
		/*testObject.put("2", "Пловдив");
		testObject.put("3", "Варна");
		testObject.put("4", "Бургас");
		testObject.put("5", "Велико Търново");
		testObject.put("6", "Плевен");
		testObject.put("7", "Стара Загора");
		testObject.put("8", "Айтос");
		testObject.put("9", "Аксаково");
		testObject.put("10", "Албена");
		testObject.put("11", "Ален мак");
		testObject.put("12", "Алфатар");
		testObject.put("13", "Антоново");
		testObject.put("14", "Априлци");
		testObject.put("15", "Арапя");
		testObject.put("16", "Ардино");
		testObject.put("17", "Асеновград");
		testObject.put("18", "Ахелой");
		testObject.put("19", "Ахтопол");
		testObject.put("20", "Балчик");
		testObject.put("21", "Банкя");
		testObject.put("22", "Банско");
		testObject.put("23", "Баня");
		testObject.put("24", "Батак");
		testObject.put("25", "Батановци");
		testObject.put("26", "Белене");
		testObject.put("27", "Белица");
		testObject.put("28", "Белово");
		testObject.put("29", "Белоградчик");
		testObject.put("30", "Белослав");
		testObject.put("31", "Берковица");
		testObject.put("32", "Благоевград");
		testObject.put("33", "Бобов дол");
		testObject.put("34", "Бобошево");
		testObject.put("35", "Божурище");
		testObject.put("36", "Бойчиновци");
		testObject.put("37", "Болярово");
		testObject.put("38", "Борово");
		testObject.put("39", "Боровец");
		testObject.put("40", "Ботевград");
		testObject.put("41", "Брацигово");
		testObject.put("42", "Брегово");
		testObject.put("43", "Брезник");
		testObject.put("44", "Брезово");
		testObject.put("45", "Брусарци");
		testObject.put("46", "Бухово");
		testObject.put("47", "Българово");
		testObject.put("48", "Бяла");
		testObject.put("49", "Бяла - Варна");
		testObject.put("50", "Бяла Слатина");
		testObject.put("51", "Бяла Черква");
		testObject.put("52", "Велики Преслав");
		testObject.put("53", "Велинград");
		testObject.put("54", "Ветово");
		testObject.put("55", "Ветрен");
		testObject.put("56", "Видин");
		testObject.put("57", "Враца");
		testObject.put("58", "Вълчедръм");
		testObject.put("59", "Вълчи дол");
		testObject.put("60", "Върбица");
		testObject.put("61", "Вършец");
		testObject.put("62", "Габрово");
		testObject.put("63", "Генерал Тошево");
		testObject.put("64", "Главиница");
		testObject.put("65", "Глоджево");
		testObject.put("66", "Годеч");
		testObject.put("67", "Горна Оряховица");
		testObject.put("68", "Гоце Делчев");
		testObject.put("69", "Градина");
		testObject.put("70", "Грамада");
		testObject.put("71", "Гулянци");
		testObject.put("72", "Гурково");
		testObject.put("73", "Гълъбово");
		testObject.put("74", "Две могили");
		testObject.put("75", "Дебелец");
		testObject.put("76", "Девин");
		testObject.put("77", "Девня");
		testObject.put("78", "Джебел");
		testObject.put("79", "Димитровград");
		testObject.put("80", "Димово");
		testObject.put("81", "Добринище");
		testObject.put("82", "Добрич");
		testObject.put("83", "Долна баня");
		testObject.put("84", "Долна Митрополия");
		testObject.put("85", "Долна Оряховица");
		testObject.put("86", "Долни Дъбник");
		testObject.put("87", "Долни чифлик");
		testObject.put("88", "Доспат");
		testObject.put("89", "Драгоман");
		testObject.put("90", "Дряново");
		testObject.put("91", "Дулово");
		testObject.put("92", "Дунавци");
		testObject.put("93", "Дупница");
		testObject.put("94", "Дългопол");
		testObject.put("95", "Дюни");
		testObject.put("96", "Евксиноград");
		testObject.put("97", "Елена");
		testObject.put("98", "Елените");
		testObject.put("99", "Елин Пелин");
		testObject.put("100", "Елхово");
		testObject.put("101", "Етрополе");
		testObject.put("102", "Завет");
		testObject.put("103", "Земен");
		testObject.put("104", "Златарица");
		testObject.put("105", "Златица");
		testObject.put("106", "Златни пясъци");
		testObject.put("107", "Златоград");
		testObject.put("108", "Ивайловград");
		testObject.put("109", "Игнатиево");
		testObject.put("110", "Иракли");
		testObject.put("111", "Искър");
		testObject.put("112", "Исперих");
		testObject.put("113", "Ихтиман");
		testObject.put("114", "Каблешково");
		testObject.put("115", "Каварна");
		testObject.put("116", "Казанлък");
		testObject.put("117", "Калофер");
		testObject.put("118", "Камено");
		testObject.put("119", "Камчия");
		testObject.put("120", "Каолиново");
		testObject.put("121", "Карандила");
		testObject.put("122", "Карлово");
		testObject.put("123", "Карнобат");
		testObject.put("124", "Каспичан");
		testObject.put("125", "Кермен");
		testObject.put("126", "Килифарево");
		testObject.put("127", "Китен");
		testObject.put("128", "Клисура");
		testObject.put("129", "Кнежа");
		testObject.put("130", "Козлодуй");
		testObject.put("131", "Койнаре");
		testObject.put("132", "Копривщица");
		testObject.put("133", "Костандово");
		testObject.put("134", "Костенец");
		testObject.put("135", "Костинброд");
		testObject.put("136", "Котел");
		testObject.put("137", "Кочериново");
		testObject.put("138", "Кресна");
		testObject.put("139", "Криводол");
		testObject.put("140", "Кричим");
		testObject.put("141", "Крумовград");
		testObject.put("142", "Кубрат");
		testObject.put("143", "Куклен");
		testObject.put("144", "Кула");
		testObject.put("145", "Кърджали");
		testObject.put("146", "Кюстендил");
		testObject.put("147", "Левски");
		testObject.put("148", "Летница");
		testObject.put("149", "Ловеч");
		testObject.put("150", "Лозенец");
		testObject.put("151", "Лозница");
		testObject.put("152", "Лом");
		testObject.put("153", "Луковит");
		testObject.put("154", "Лъки");
		testObject.put("155", "Любимец");
		testObject.put("156", "Лясковец");
		testObject.put("157", "Мадан");
		testObject.put("158", "Маджарово");
		testObject.put("159", "Малко Търново");
		testObject.put("160", "Мартен");
		testObject.put("161", "Мездра");
		testObject.put("162", "Мелник");
		testObject.put("163", "Меричлери");
		testObject.put("164", "Мизия");
		testObject.put("165", "Момин проход");
		testObject.put("166", "Момчилград");
		testObject.put("167", "Монтана");
		testObject.put("168", "Мъглиж");
		testObject.put("169", "Неделино");
		testObject.put("170", "Несебър");
		testObject.put("171", "Николаево");
		testObject.put("172", "Никопол");
		testObject.put("173", "Нова Загора");
		testObject.put("174", "Нови Искър");
		testObject.put("175", "Нови пазар");
		testObject.put("176", "Обзор");
		testObject.put("177", "Омуртаг");
		testObject.put("178", "Опака");
		testObject.put("179", "Оряхово");
		testObject.put("180", "Павел баня");
		testObject.put("181", "Павликени");
		testObject.put("182", "Пазарджик");
		testObject.put("183", "Панагюрище");
		testObject.put("184", "Пампорово");
		testObject.put("185", "Паша дере");
		testObject.put("186", "Перник");
		testObject.put("187", "Перущица");
		testObject.put("188", "Петрич");
		testObject.put("189", "Пещера");
		testObject.put("190", "Пирдоп");
		testObject.put("191", "Плачковци");
		testObject.put("192", "Плиска");
		testObject.put("193", "Полски Тръмбеш");
		testObject.put("194", "Поморие");
		testObject.put("195", "Попово");
		testObject.put("196", "Пордим");
		testObject.put("197", "Правец");
		testObject.put("198", "Приморско");
		testObject.put("199", "Провадия");
		testObject.put("200", "Първомай");
		testObject.put("201", "Раднево");
		testObject.put("202", "Радомир");
		testObject.put("203", "Разград");
		testObject.put("204", "Разлог");
		testObject.put("205", "Ракитово");
		testObject.put("206", "Раковски");
		testObject.put("207", "Рила");
		testObject.put("208", "Роман");
		testObject.put("209", "Романтика");
		testObject.put("210", "Рудозем");
		testObject.put("211", "Русалка");
		testObject.put("212", "Русе");
		testObject.put("213", "Садово");
		testObject.put("214", "Самоков");
		testObject.put("215", "Сандански");
		testObject.put("216", "Сапарева баня");
		testObject.put("217", "Св. св. Константин и Елена");
		testObject.put("218", "Свети Влас");
		testObject.put("219", "Свиленград");
		testObject.put("220", "Свищов");
		testObject.put("221", "Своге");
		testObject.put("222", "Севлиево");
		testObject.put("223", "Сеново");
		testObject.put("224", "Септември");
		testObject.put("225", "Силистра");
		testObject.put("226", "Симеоновград");
		testObject.put("227", "Симитли");
		testObject.put("228", "Славяново");
		testObject.put("229", "Сливен");
		testObject.put("230", "Сливница");
		testObject.put("231", "Сливо поле");
		testObject.put("232", "Слънчев бряг");
		testObject.put("233", "Смолян");
		testObject.put("234", "Смокиня");
		testObject.put("235", "Смядово");
		testObject.put("236", "Созопол");
		testObject.put("237", "Сопот");
		testObject.put("238", "Средец");
		testObject.put("239", "Стамболийски");
		testObject.put("240", "Стражица");
		testObject.put("241", "Стралджа");
		testObject.put("242", "Стрелча");
		testObject.put("243", "Суворово");
		testObject.put("244", "Сунгурларе");
		testObject.put("245", "Сухиндол");
		testObject.put("246", "Съединение");
		testObject.put("247", "Сърница");
		testObject.put("248", "Твърдица");
		testObject.put("249", "Тервел");
		testObject.put("250", "Тетевен");
		testObject.put("251", "Тополовград");
		testObject.put("252", "Троян");
		testObject.put("253", "Трън");
		testObject.put("254", "Тръстеник");
		testObject.put("255", "Трявна");
		testObject.put("256", "Тутракан");
		testObject.put("257", "Търговище");
		testObject.put("258", "Угърчин");
		testObject.put("259", "Хаджидимово");
		testObject.put("260", "Харманли");
		testObject.put("261", "Хасково");
		testObject.put("262", "Хисаря");
		testObject.put("263", "Цар Калоян");
		testObject.put("264", "Царево");
		testObject.put("265", "Чепеларе");
		testObject.put("266", "Червен бряг");
		testObject.put("267", "Черноморец");
		testObject.put("268", "Чипровци");
		testObject.put("269", "Чирпан");
		testObject.put("270", "Шабла");
		testObject.put("271", "Шивачево");
		testObject.put("272", "Шипка");
		testObject.put("273", "Шумен");
		testObject.put("274", "Ябланица");
		testObject.put("275", "Якоруда");
		testObject.put("276", "Ямбол");*/
	}

}
